apiVersion: v1
kind: Service
metadata:
  name: {{ include "alert-history.fullname" . }}
  labels:
    app: {{ include "alert-history.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "alert-history.name" . }}
    release: {{ .Release.Name }}
